# Generated by Django 4.2.20 on 2025-04-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('learner', 'Learner'), ('admin', 'Admin')], default='learner', max_length=10),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
